### ISSUE TITLE
erreur ns3 

### ISSUE THREAD

**Issue by Y-AMDIAZ** [m-wojnar/reinforced-lib#39]
![image](https://user-images.githubusercontent.com/129278941/230049651-9198d5e3-8e1e-44a2-b8a7-4fe29905dc3a.png)
please I m bloked here , I dont know what is going on here please

**Comment by m-wojnar** [comment]
In this version of ns-3, the command to run the simulation is `./ns3 run`, not `./ns3 --run`, hence the problem with running the code. 

Anyway, I'm afraid the simulation you're using isn't from our repository, so if you have any further problems with ns-3 or this code, you should seek support from the ns-3 groups or their repository. If you have problems integrating ns-3 with Python, then please contact the developers of ns3-ai. However, if the case concerns a problem with our library, feel free to contact us.
